### ISSUE TITLE
Scale deployment to 0 instead of delete

### ISSUE THREAD

**Issue by hawksight** [TwiN/k8s-ttl-controller#40]
### Describe the feature request

It would be nice to have the option to scale applicable resources rather than delete, eg a `Deployment`.
This is so you can still save the resources of not having replicas running but keep the actual deployment resource in the cluster. So when a team returns to the application it's simply a case of scaling the deployment again

### Why do you personally want this feature to be implemented?

- Make it easier to scale temporary workloads down to save computing power on my local cluster.
- Also would be helpful in a GitOps pattern as replicas are easy to ignore changes to, but ignoring a whole resource is more difficult and defeats the point of GitOps a bit.
- Enable a cluster operator to recover resources from tenants easily without completely deleting resources.

### How long have you been using this project?

couple of weeks just exploring it

### Additional information

Perhaps could be implemented as a second annotation:

```yaml
k8s-ttl-controller.twin.sh/type="scale" # default "delete" if not specified, reject other values
```

Maybe this crosses over to HPA territory, but I was just looking for a simple solution, which this operator provides, one that doesn't require prior setup or additional yaml, only an annotation, or two :)

**Comment by TwiN** [comment]
@hawksight I think this is an excellent idea, however:
1. You mentioned rejecting values other than `scale` or `delete` for the `k8s-ttl-controller.twin.sh/type` annotation - this I disagree with, because `rejecting` would imply having to make k8s-ttl-controller a webhook. I think it would be better to simply ignore types that are not supported.
2. This feature _may_ be a little counter-intuitive for this project. What you're looking for is something like https://github.com/hjacobs/kube-downscaler (which seems to have now moved to https://codeberg.org/hjacobs/kube-downscaler?), and I wonder if it makes sense to add a resource-specific behavior (e.g. scaling down a Deployment or a StatefulSet) to an application (k8s-ttl-controller) configured to be as generic as possible (by using Kubernetes' dynamic client): https://github.com/TwiN/k8s-ttl-controller/blob/925270c76341eacca863cd84a50e53e09bf3f64a/main.go#L146 

It's an interesting feature, don't get me wrong, I'm just wondering about whether it makes sense.

**Comment by hawksight** [comment]
Hey @TwiN thanks for responding, I think you are correct on both points.

1. Yes it was a poor choice of words on my part. Ignore is what I meant in my head :)
2. That project looks to do the scaling part of what I was looking for.

I'll give that project a try and close this issue for now. I'll re-open this if I find a good reason. I think I knew making that scaling decision would add a lot of complexity and corner cases.
