### ISSUE TITLE
TTL notification 

### ISSUE THREAD

**Issue by ahadrez** [TwiN/k8s-ttl-controller#79]
### Describe the feature request

I was wondering if you're planning to add notifications via email to send notifications when ttl about to expire.

**Comment by TwiN** [comment]
I don't think this is appropriate for an application like this.

That being said, k8s-ttl-controller _does_ create events when resources are deleted due to TTL: https://github.com/TwiN/k8s-ttl-controller/blob/e322d7e7bb8a7ef4a91e1743ed5a4e188a4aed3e/main.go#L153

It's not quite what you're looking for, but this coupled with alertmanager should allow you to create notifications when deletions occur.
